export const algogrindEdgelessLightColors = {
  '--algogrind-note-background-red': ' #fecaca',
  '--algogrind-note-background-orange': ' #fed7aa',
  '--algogrind-note-background-yellow': ' #fef08a',
  '--algogrind-note-background-green': ' #bbf7d0',
  '--algogrind-note-background-teal': ' #99f6e4',
  '--algogrind-note-background-blue': ' #bfdbfe',
  '--algogrind-note-background-purple': ' #e9d5ff',
  '--algogrind-note-background-pink': ' #fbcfe8',
  '--algogrind-note-background-grey': ' #e5e7eb',
  '--algogrind-note-background-black': ' rgba(0, 0, 0, 1)',
  '--algogrind-note-background-white': ' rgba(255, 255, 255, 1)',
  '--algogrind-palette-shape-red': ' #fca5a5',
  '--algogrind-palette-shape-orange': ' #fdba74',
  '--algogrind-palette-shape-yellow': ' #fcd34d',
  '--algogrind-palette-shape-lime': ' #bef264',
  '--algogrind-palette-shape-green': ' #86efac',
  '--algogrind-palette-shape-teal': ' #5eead4',
  '--algogrind-palette-shape-blue': ' #93c5fd',
  '--algogrind-palette-shape-purple': ' #d8b4fe',
  '--algogrind-palette-shape-pink': ' #f9a8d4',
  '--algogrind-palette-shape-grey': ' #d1d5db',
  '--algogrind-palette-shape-black': ' rgba(0, 0, 0, 1)',
  '--algogrind-palette-shape-white': ' rgba(255, 255, 255, 1)',
  '--algogrind-palette-line-red': ' #ef4444',
  '--algogrind-palette-line-orange': ' #f97316',
  '--algogrind-palette-line-yellow': ' #eab308',
  '--algogrind-palette-line-lime': ' #84cc16',
  '--algogrind-palette-line-green': ' #22c55e',
  '--algogrind-palette-line-teal': ' #14b8a6',
  '--algogrind-palette-line-blue': ' #3b82f6',
  '--algogrind-palette-line-purple': ' #a855f7',
  '--algogrind-palette-line-pink': ' #ec4899',
  '--algogrind-palette-line-grey': ' #6b7280',
  '--algogrind-palette-line-black': ' rgba(0, 0, 0, 1)',
  '--algogrind-palette-line-white': ' rgba(255, 255, 255, 1)',
} as const;

export const algogrindEdgelessDarkColors = {
  '--algogrind-note-background-red': ' #fecaca',
  '--algogrind-note-background-orange': ' #fed7aa',
  '--algogrind-note-background-yellow': ' #fef08a',
  '--algogrind-note-background-green': ' #bbf7d0',
  '--algogrind-note-background-teal': ' #99f6e4',
  '--algogrind-note-background-blue': ' #bfdbfe',
  '--algogrind-note-background-purple': ' #e9d5ff',
  '--algogrind-note-background-pink': ' #fbcfe8',
  '--algogrind-note-background-grey': ' #e5e7eb',
  '--algogrind-note-background-black': ' rgba(0, 0, 0, 1)',
  '--algogrind-note-background-white': ' rgba(255, 255, 255, 1)',
  '--algogrind-palette-shape-red': ' #fca5a5',
  '--algogrind-palette-shape-orange': ' #fdba74',
  '--algogrind-palette-shape-yellow': ' #fcd34d',
  '--algogrind-palette-shape-lime': ' #bef264',
  '--algogrind-palette-shape-green': ' #86efac',
  '--algogrind-palette-shape-teal': ' #5eead4',
  '--algogrind-palette-shape-blue': ' #93c5fd',
  '--algogrind-palette-shape-purple': ' #d8b4fe',
  '--algogrind-palette-shape-pink': ' #f9a8d4',
  '--algogrind-palette-shape-grey': ' #d1d5db',
  '--algogrind-palette-shape-black': ' rgba(0, 0, 0, 1)',
  '--algogrind-palette-shape-white': ' rgba(255, 255, 255, 1)',
  '--algogrind-palette-line-red': ' #ef4444',
  '--algogrind-palette-line-orange': ' #f97316',
  '--algogrind-palette-line-yellow': ' #eab308',
  '--algogrind-palette-line-lime': ' #84cc16',
  '--algogrind-palette-line-green': ' #22c55e',
  '--algogrind-palette-line-teal': ' #14b8a6',
  '--algogrind-palette-line-blue': ' #3b82f6',
  '--algogrind-palette-line-purple': ' #a855f7',
  '--algogrind-palette-line-pink': ' #ec4899',
  '--algogrind-palette-line-grey': ' #6b7280',
  '--algogrind-palette-line-black': ' rgba(0, 0, 0, 1)',
  '--algogrind-palette-line-white': ' rgba(255, 255, 255, 1)',
} as const;
